/**
 * This code was generated by Builder.io.
 */
import React from "react";

const AsswifHeistSection: React.FC = () => {
  return (
    <section className="flex flex-col items-center px-16 pt-12 -mb-0.5 w-full bg-black bg-center bg-no-repeat bg-cover bg-[url(https://cdn.builder.io/api/v1/image/assets%2F9f29ed1c16be4e17a4743a02b9341082%2F2e4c6712ec074d37a6122047d73d88e2)] max-md:px-5 max-md:max-w-full">
      <div className="flex flex-col px-12 pt-16 pb-4 -mb-px max-w-full bg-neutral-800 w-[896px] max-md:px-5">
        <h2 className="flex flex-col justify-center text-5xl font-bold leading-10 text-sky-400 max-md:max-w-full max-md:text-4xl">
          <div className="text-red-700 max-md:max-w-full max-md:text-4xl">
            <p>The Great ASSWIF Heist: Bringing Julian Home</p>
          </div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets%2F9f29ed1c16be4e17a4743a02b9341082%2Feaeb8ee221134b3ba16a9cdf9c3fc8b8"
            alt=""
            className="box-border object-cover overflow-hidden shrink-0 mt-5 w-full aspect-square min-h-[20px] min-w-[20px]"
          />
        </h2>
        <div className="flex flex-col mt-6 max-md:max-w-full">
          <div className="flex flex-col justify-center text-lg leading-7 text-sky-100 max-md:max-w-full" />
          <div className="flex justify-center items-center mt-8 max-md:max-w-full" />
        </div>
      </div>
    </section>
  );
};

export default AsswifHeistSection;
