/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Footer: React.FC = () => {
  return (
    <footer className="box-border flex relative flex-col shrink-0 justify-center py-5 bg-black">
      <div className="flex gap-5 gap-5 gap-x-5 gap-x-5 gap-y-5 gap-y-5 mx-auto">
        <img
          loading="lazy"
          alt=""
          src="https://cdn.builder.io/api/v1/image/assets%2F9f29ed1c16be4e17a4743a02b9341082%2Ff69a4c9f3dc94fbe8afdf7f03b537735"
          className="object-contain aspect-square min-h-[150px] w-[150px] max-md:w-[30px] max-sm:w-[100px]"
        />
        <img
          loading="lazy"
          alt=""
          src="https://cdn.builder.io/api/v1/image/assets%2F9f29ed1c16be4e17a4743a02b9341082%2F1f275be90f4e4c758e44bb083b48c987"
          className="object-contain aspect-square min-h-[150px] w-[150px] max-md:w-[30px] max-sm:w-[100px]"
        />
        <img
          loading="lazy"
          alt=""
          src="https://cdn.builder.io/api/v1/image/assets%2F9f29ed1c16be4e17a4743a02b9341082%2F30fb670ac6804328b880b18d9e034759"
          className="object-contain aspect-square min-h-[150px] w-[150px] max-md:w-[30px] max-sm:w-[100px]"
        />
      </div>
    </footer>
  );
};

export default Footer;
