/**
 * This code was generated by Builder.io.
 */
import React from "react";

const GetAsswifButton: React.FC = () => {
  return (
    <div className="flex flex-col justify-center self-stretch px-5 my-auto max-md:max-w-full max-sm:mr-0 max-sm:ml-14">
      <div className="flex flex-col justify-center items-end px-16 max-md:pl-5 max-md:max-w-full max-sm:ml-px">
        <div className="flex flex-col justify-center max-w-full w-[175px]">
          <div className="flex flex-col justify-center p-px bg-violet-600 bg-opacity-90">
            <div className="flex flex-col justify-center px-3 py-1.5 w-full bg-red-600 max-sm:mx-auto">
              <div className="flex gap-2">
                <div className="text-sm font-bold leading-6 text-center text-white">
                  <p>Get ASSWIF</p>
                </div>
                <div className="flex gap-0.5 justify-center py-1">
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/8488ec592d7a6185681238986214eabad0463a3bf12814a0766756a649d7a4ea?apiKey=694293a9ea8f4bb0887f6c4f9a7367c3&"
                    alt=""
                    className="shrink-0 w-4 aspect-square"
                  />
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/d0c55f2f05f56d4dbe76658a8ad17356a205216004beffc2576e14ce041ec684?apiKey=694293a9ea8f4bb0887f6c4f9a7367c3&"
                    alt=""
                    className="shrink-0 aspect-[1.37] w-[22px]"
                  />
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/0e79b7a5be8f307d260368ba96e6cb73a0382e0f38f21ba88d59fd1f9b2d8ea1?apiKey=694293a9ea8f4bb0887f6c4f9a7367c3&"
                    alt=""
                    className="shrink-0 w-4 aspect-square"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default GetAsswifButton;
