/**
 * This code was generated by Builder.io.
 */
import React from "react";
import NavItem from "./NavItem";
import GetAsswifButton from "./GetAsswifButton";
import { NAV_ITEMS } from "../utils/constants";

const Header: React.FC = () => {
  return (
    <header className="flex flex-col mb-0 w-full max-md:max-w-full">
      <nav className="flex flex-col justify-center py-2 w-full bg-black max-md:max-w-full">
        <div className="flex gap-0 justify-between items-center py-3 pr-7 pl-7 w-full max-md:flex-wrap max-md:px-5 max-md:max-w-full max-sm:pr-3.5">
          <div className="flex flex-col justify-center items-start self-stretch max-md:max-w-full">
            <div className="flex justify-center items-center p-1.5 w-[50px]" />
          </div>
          <div className="flex gap-5 justify-between self-stretch pr-1.5 my-auto text-base font-bold leading-6 text-sky-100 whitespace-nowrap max-md:flex-wrap max-md:max-w-full">
            {NAV_ITEMS.map((item, index) => (
              <NavItem key={index} label={item.label} link={item.link} />
            ))}
          </div>
          <GetAsswifButton />
        </div>
      </nav>
      <div className="flex flex-col justify-center px-3.5 py-2.5 w-full text-sm leading-6 text-sky-100 bg-neutral-600 max-md:max-w-full max-sm:bg-black">
        <div className="flex justify-center items-center px-16 max-md:px-5 max-md:max-w-full">
          <div className="justify-center max-md:pr-5 max-md:max-w-full">
            <p className="indent-[2em]">
              The <strong>ASSWIF Token </strong>is live now! EVM compatible, low
              transaction fees, and saving Julian Assange's ass one bribe at
              time.
            </p>
          </div>
        </div>
      </div>
    </header>
  );
};

export default Header;
