/**
 * This code was generated by Builder.io.
 */
import React from "react";
import StatItem from "./StatItem";
import { HERO_STATS } from "../utils/constants";

const HeroSection: React.FC = () => {
  return (
    <section className="flex justify-center items-center pt-12 pb-52 w-full bg-center bg-no-repeat bg-cover bg-[url(https://cdn.builder.io/api/v1/image/assets%2F9f29ed1c16be4e17a4743a02b9341082%2F1e606b84d4ea4fe0b059782cadddf640)] bg-black bg-opacity-30 h-[1990px] max-md:px-5 max-md:max-w-full max-sm:flex max-sm:flex-row max-sm:flex-wrap max-sm:pb-20 max-sm:bg-black max-sm:h-[1120px]">
      <div className="flex flex-col px-12 py-16 -mb-0.5 max-w-full bg-neutral-800 w-[896px] max-md:px-5 max-sm:pt-6 max-sm:pb-20">
        <h1 className="justify-center pr-24 text-7xl font-bold text-red-700 leading-[72px] max-md:max-w-full max-md:text-4xl max-md:leading-10 max-sm:pr-0 max-sm:text-red-700">
          Kick the hornets' nest. CRYPTO to Back ASSANGE + LEAKS
        </h1>
        <p className="justify-center mt-6 text-xl leading-7 text-sky-100 max-md:max-w-full">
          Launched in JUNE 2024, an ERC-20 token has reshaped the ecosystem by
          enabling users to reward others for posting quality content. Our
          points system recognizes unique posts and comments, effectively
          bridging the gap between online contributions and real-world value.
        </p>
        <div className="flex gap-5 justify-between items-start pt-10 mt-6 text-right max-md:flex-wrap max-md:max-w-full max-sm:pl-12 max-sm:-mx-px">
          {HERO_STATS.map((stat, index) => (
            <StatItem key={index} label={stat.label} value={stat.value} />
          ))}
        </div>
      </div>
    </section>
  );
};

export default HeroSection;
