/**
 * This code was generated by Builder.io.
 */
export interface NavItemType {
  label: string;
  link: string;
}

export interface StatItemType {
  label: string;
  value: string;
}

export interface PlanPhaseType {
  title: string;
  date: string;
  objective: string;
  plan: string[];
}
