/**
 * This code was generated by Builder.io.
 */
import React from "react";

type NavItemProps = {
  label: string;
  link: string;
};

const NavItem: React.FC<NavItemProps> = ({ label, link }) => {
  return (
    <div className="flex flex-col justify-center text-center">
      <div className="flex gap-1">
        <a href={link} className="justify-center pr-px">
          {label}
        </a>
      </div>
    </div>
  );
};

export default NavItem;
