/**
 * This code was generated by Builder.io.
 */
import React from "react";
import StatItem from "./StatItem";
import { PLAN_PHASES, PLAN_STATS } from "../utils/constants";

const PlanSection: React.FC = () => {
  return (
    <section className="flex justify-center items-center px-16 -mt-1 w-full bg-black max-md:px-5 max-md:max-w-full max-sm:mb-0">
      <div className="flex flex-col px-12 pb-16 -mt-0.5 mb-52 max-w-full bg-neutral-800 w-[896px] max-md:px-5 max-sm:pb-6">
        <div className="justify-center pt-0 mt-6 text-xl leading-7 text-sky-100 max-md:max-w-full">
          {PLAN_PHASES.map((phase, index) => (
            <div key={index}>
              <h3 className="text-2xl font-bold">{phase.title}</h3>
              <p>Date: {phase.date}</p>
              <p>Objective: {phase.objective}</p>
              <p>Plan:</p>
              <ul>
                {phase.plan.map((step, stepIndex) => (
                  <li key={stepIndex}>{step}</li>
                ))}
              </ul>
            </div>
          ))}
          <p>
            Although this plan is a humorous take on the situation, we do feel
            that something should truly happen. Considering the value of our
            tokens and the potential impact, we are serious about bringing
            freedom to those who reveal the truth.
          </p>
          <p>
            Each of these targets has a bounty page where you can see how much
            we have allocated and how much we can pay them. We have even set up
            wallets for these figures if they are willing to assist in the
            mission. Check out our bounty page for more details and join us in
            this revolutionary endeavor.
          </p>
        </div>
        <div className="flex gap-5 justify-between items-start pt-10 mt-6 text-right max-md:flex-wrap max-md:max-w-full">
          {PLAN_STATS.map((stat, index) => (
            <StatItem key={index} label={stat.label} value={stat.value} />
          ))}
        </div>
      </div>
    </section>
  );
};

export default PlanSection;
