/**
 * This code was generated by Builder.io.
 */
import React from "react";

type StatItemProps = {
  label: string;
  value: string;
};

const StatItem: React.FC<StatItemProps> = ({ label, value }) => {
  return (
    <div className="flex flex-col whitespace-nowrap">
      <div className="justify-center text-base leading-6 text-sky-400 max-sm:px-5">
        <p>{label}</p>
      </div>
      <div className="justify-center text-2xl font-bold leading-8 text-sky-100 max-sm:px-5">
        {value}
      </div>
    </div>
  );
};

export default StatItem;
