/**
 * This code was generated by Builder.io.
 */
import { NavItemType, StatItemType, PlanPhaseType } from "../types";

export const NAV_ITEMS: NavItemType[] = [
  { label: "Airdrops", link: "#" },
  { label: "BOUNTY", link: "#" },
  { label: "Tokenomics", link: "#" },
];

export const HERO_STATS: StatItemType[] = [
  { label: "Hodling Crypto", value: "since 2011" },
  { label: "War crimes exposed", value: "31932" },
  { label: "Corrupt Ppl Exposed", value: "21938" },
];

export const PLAN_PHASES: PlanPhaseType[] = [
  {
    title: 'Phase 1: "Operation Bribe the Driver"',
    date: "June 25, 2024",
    objective: "Identify and bribe the driver transporting Julian Assange.",
    plan: [
      "Raise the value of ASSWIF to astronomical heights.",
      "Transfer a hefty sum of ASSWIF to a secret wallet.",
      'Approach the driver with an offer he can\'t refuse: a lifetime supply of ASSWIF in exchange for a "detour."',
    ],
  },
  {
    title: 'Phase 2: "Fly Me to the Moon"',
    date: "July 5, 2024",
    objective: "Redirect the plane transporting Assange to America.",
    plan: [
      "Identify the pilot of the extradition flight.",
      "Offer the pilot an insane amount of ASSWIF to change course.",
      "Destination: An undisclosed tropical island with no extradition treaty.",
    ],
  },
  {
    title: 'Phase 3: "Face/Off - The Silicone Heist"',
    date: "July 15, 2024",
    objective: "Get Julian a silicone prosthetic mask.",
    plan: [
      "Hire top-notch Hollywood makeup artists.",
      "Create a John Travolta-like mask, complete with hair and swagger.",
      "Smuggle the mask into the jail using a cleverly disguised cake.",
    ],
  },
  {
    title: 'Phase 4: "The Great Escape"',
    date: "July 20, 2024",
    objective: "Sneak Julian out of jail.",
    plan: [
      "Coordinate with insiders (bribed with ASSWIF) to get Julian into the disguise.",
      "Use a series of misdirections to distract the guards.",
      "Julian, now looking like a completely different person, walks out casually.",
    ],
  },
  {
    title: 'Phase 5: "The Final Act"',
    date: "July 25, 2024",
    objective: "Secure Julian's freedom.",
    plan: [
      "Arrange a private jet, piloted by yet another highly paid (in ASSWIF) accomplice.",
      "Fly Julian to the secret island.",
      "Announce to the world that Julian is free, thanks to the power of ASSWIF!",
    ],
  },
  {
    title: 'Bonus Phase: "Operation FaceTime with George"',
    date: "July 30, 2024",
    objective: "Distract the senior CIA officials.",
    plan: [
      "Arrange a fake FaceTime call with George Bush, using a deepfake technology.",
      "Make George Bush deliver an impromptu comedy routine about his painting hobby and his dog's antics.",
      "Ensure all senior CIA officials are too engrossed in the hilarity to notice Julian's escape.",
    ],
  },
];

export const PLAN_STATS: StatItemType[] = [
  { label: "Holders", value: "465k" },
  { label: "Transactions", value: "6.00M" },
  { label: "Fully Diluted Market Cap", value: "$358.23M" },
  { label: "Price", value: "$0.010" },
];
