/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Layout from "../components/Layout";
import HeroSection from "../components/HeroSection";
import AsswifHeistSection from "../components/AsswifHeistSection";
import PlanSection from "../components/PlanSection";

const HomePage: React.FC = () => {
  return (
    <Layout>
      <HeroSection />
      <AsswifHeistSection />
      <PlanSection />
    </Layout>
  );
};

export default HomePage;
